#!/bin/bash




# ========== ETL commands ===========
dry-run() {
    docker compose exec django python -m core.manage load_tax_registration --limit 10000 --dry-run

}

update-import() {
    python -m core.manage load_tax_registration --truncate

}

resume() {
    python -m core.manage load_tax_registration --resume
}

# ========== Django cocmmands ===========

server() {
    python -m core.manage runserver
}

create-admin() {

    python -m core.manage createsuperuser --noinput || echo "超級管理員可能已存在，跳過建立。"
}

migrations() {
    python -m core.manage makemigrations $@
}

migrate() {
    python -m core.manage migrate
}


# ========== Docker cocmmands ===========

up() {
    docker-compose -f docker-compose.yml up $@ --build -d 
}

down() {
    docker-compose -f docker-compose.yml down
}

app-shell() {
    docker compose exec django bash
}

shell() {
    poetry run python -m core.manage shell
}


# ========== QA cocmmands ===========
lint() {
    git add .; poetry run pre-commit run --all-files 
}


help() {
    echo "${1} <task> <arg>s"
    echo "Tasks:"
    compgen -A function | cat -n 
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
