# Generated by Django 6.0.1 on 2026-01-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxRegistration",
            fields=[
                (
                    "ban",
                    models.CharField(
                        db_index=True,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="統一編號",
                    ),
                ),
                (
                    "headquarters_ban",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="總機構統一編號",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="營業人名稱"
                    ),
                ),
                (
                    "business_address",
                    models.CharField(max_length=255, verbose_name="營業地址"),
                ),
                (
                    "capital_amount",
                    models.IntegerField(blank=True, null=True, verbose_name="資本額"),
                ),
                (
                    "established_date",
                    models.CharField(max_length=7, verbose_name="設立日期"),
                ),
                (
                    "business_type",
                    models.CharField(max_length=100, verbose_name="組織別"),
                ),
                (
                    "is_use_invoice",
                    models.BooleanField(default=False, verbose_name="使用統一發票"),
                ),
                (
                    "industry_code",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="行業代號"
                    ),
                ),
                (
                    "industry_name",
                    models.CharField(max_length=100, verbose_name="行業名稱"),
                ),
                (
                    "industry_code_1",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="行業代號1"
                    ),
                ),
                (
                    "industry_name_1",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="行業名稱1"
                    ),
                ),
                (
                    "industry_code_2",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="行業代號2"
                    ),
                ),
                (
                    "industry_name_2",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="行業名稱2"
                    ),
                ),
                (
                    "industry_code_3",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="行業代號3"
                    ),
                ),
                (
                    "industry_name_3",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="行業名稱3"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "營業登記",
                "verbose_name_plural": "營業登記",
                "indexes": [
                    models.Index(
                        fields=["business_name"], name="tax_registr_busines_07d9ba_idx"
                    ),
                    models.Index(
                        fields=["industry_code"], name="tax_registr_industr_366680_idx"
                    ),
                ],
            },
        ),
    ]
