# Generated by Django 6.0.1 on 2026-01-25 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tax_registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxregistration",
            name="business_name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="營業人名稱"
            ),
        ),
        migrations.AlterField(
            model_name="taxregistration",
            name="business_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="組織別名稱"
            ),
        ),
        migrations.AlterField(
            model_name="taxregistration",
            name="capital_amount",
            field=models.BigIntegerField(
                db_index=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="資本額",
            ),
        ),
        migrations.AlterField(
            model_name="taxregistration",
            name="headquarters_ban",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="總機構統一編號必須是 8 位數字", regex="^\\d{8}$"
                    )
                ],
                verbose_name="總機構統一編號",
            ),
        ),
    ]
