# Generated by Django 6.0.1 on 2026-01-25 07:43

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tax_registration", "0002_alter_taxregistration_business_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxregistration",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="建立時間",
            ),
        ),
        migrations.AlterField(
            model_name="taxregistration",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="更新時間",
            ),
        ),
    ]
