# Generated by Django 6.0.1 on 2026-01-24 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ETLJobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="開始時間"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成時間"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "執行中"),
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("partial", "部分成功"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "records_total",
                    models.IntegerField(default=0, verbose_name="總筆數"),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="處理成功筆數"),
                ),
                (
                    "records_failed",
                    models.IntegerField(default=0, verbose_name="失敗筆數"),
                ),
                (
                    "records_duplicated",
                    models.IntegerField(default=0, verbose_name="重複筆數"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="錯誤訊息"),
                ),
                (
                    "batch_size",
                    models.IntegerField(default=10000, verbose_name="批次大小"),
                ),
                (
                    "chunk_size",
                    models.IntegerField(default=50000, verbose_name="Chunk 大小"),
                ),
                (
                    "data_source_url",
                    models.URLField(blank=True, verbose_name="資料來源網址"),
                ),
            ],
            options={
                "verbose_name": "ETL執行紀錄",
                "verbose_name_plural": "ETL執行紀錄",
                "db_table": "etl_job_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxRegistration",
            fields=[
                (
                    "ban",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="統一編號必須是 8 位數字", regex="^\\d{8}$"
                            )
                        ],
                        verbose_name="統一編號",
                    ),
                ),
                (
                    "headquarters_ban",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="總機構統一編號必須是 8 位數字",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="總機構統一編號",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=255, verbose_name="營業人名稱"),
                ),
                (
                    "business_address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="營業地址"
                    ),
                ),
                (
                    "capital_amount",
                    models.BigIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="資本額",
                    ),
                ),
                (
                    "business_setup_date",
                    models.CharField(
                        blank=True,
                        help_text="格式: YYYYMMDD",
                        max_length=8,
                        verbose_name="設立日期",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="組織別名稱"
                    ),
                ),
                (
                    "is_use_invoice",
                    models.BooleanField(default=False, verbose_name="使用統一發票"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "data_source_date",
                    models.DateField(
                        blank=True,
                        help_text="CSV 檔案的日期",
                        null=True,
                        verbose_name="資料來源日期",
                    ),
                ),
            ],
            options={
                "verbose_name": "營業登記",
                "verbose_name_plural": "營業登記",
                "db_table": "tax_registration",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_successful_batch",
                    models.IntegerField(default=0, verbose_name="最後成功批次"),
                ),
                (
                    "total_batches",
                    models.IntegerField(default=0, verbose_name="總批次數"),
                ),
                (
                    "current_batch",
                    models.IntegerField(default=0, verbose_name="當前批次"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "job_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="tax_registration.etljobrun",
                        verbose_name="ETL執行",
                    ),
                ),
            ],
            options={
                "verbose_name": "匯入進度",
                "verbose_name_plural": "匯入進度",
                "db_table": "import_progress",
            },
        ),
        migrations.CreateModel(
            name="DataImportError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.IntegerField(verbose_name="批次編號")),
                (
                    "error_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="錯誤類型"
                    ),
                ),
                ("error_message", models.TextField(verbose_name="錯誤訊息")),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        help_text="導致錯誤的原始資料(JSON格式)",
                        null=True,
                        verbose_name="原始資料",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="建立時間"
                    ),
                ),
                (
                    "job_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="tax_registration.etljobrun",
                        verbose_name="ETL執行",
                    ),
                ),
            ],
            options={
                "verbose_name": "匯入錯誤紀錄",
                "verbose_name_plural": "匯入錯誤紀錄",
                "db_table": "data_import_error",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["error_type", "created_at"], name="idx_err_type_time"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="行業代號",
                    ),
                ),
                (
                    "industry_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="行業名稱"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="第1、2、3、4個行業", verbose_name="順序"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industries",
                        to="tax_registration.taxregistration",
                        verbose_name="營業人",
                    ),
                ),
            ],
            options={
                "verbose_name": "營業項目",
                "verbose_name_plural": "營業項目",
                "db_table": "business_industry",
                "ordering": ["business", "order"],
                "indexes": [
                    models.Index(
                        fields=["industry_code", "business"], name="idx_ind_code_biz"
                    )
                ],
                "unique_together": {("business", "industry_code")},
            },
        ),
    ]
