# Generated by Django 6.0.1 on 2026-01-27 13:33

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tax_registration", "0003_alter_taxregistration_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="businessindustry",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="taxregistration",
            name="data_source_date",
            field=models.DateField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                help_text="CSV 檔案的日期",
                null=True,
                verbose_name="資料來源日期",
            ),
        ),
        migrations.AddConstraint(
            model_name="businessindustry",
            constraint=models.UniqueConstraint(
                fields=("business", "industry_code"), name="unique_business_industry"
            ),
        ),
    ]
