# Generated by Django 6.0.1 on 2026-01-29 05:26

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tax_registration", "0004_alter_businessindustry_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="etljobrun",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                verbose_name="更新時間",
            ),
        ),
    ]
