# Generated by Django 6.0.1 on 2026-02-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tax_registration", "0005_etljobrun_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(unique=True, verbose_name="資料來源 URL"),
                ),
                (
                    "etag",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="ETag"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="內容 Hash"
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(auto_now=True, verbose_name="上次檢查時間"),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次實際更新時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "資料來源 metadata",
                "db_table": "data_source_metadata",
            },
        ),
    ]
